// Every threshold the dashboard uses lives here. Values are demo-tuned, not validated.

export const rules = {
  freshness: {
    stale_after_s: 15,
    offline_after_s: 60,
  },

  alerts: {
    // An alert closes only after its field has been back within limits this long.
    clear_after_s: 10,
  },

  sos: {
    // Possible collision (heuristic): speed falls from >= from_kmh to <= to_kmh within within_s.
    collision: { from_kmh: 40, to_kmh: 5, within_s: 3 },
  },

  ingest: {
    // Points stamped this far ahead of the BFF clock are dropped (device clock not set yet).
    max_future_s: 300,
  },

  health: [
    {
      id: 'coolant_temp_critical',
      name: 'Coolant critical',
      field: 'coolant_temp',
      op: '>',
      threshold: 110,
      level: 'critical',
      unit: '°C',
      description: 'Coolant well above normal operating range; risk of overheating.',
    },
    {
      id: 'coolant_temp_warning',
      name: 'Coolant high',
      field: 'coolant_temp',
      op: '>',
      threshold: 100,
      level: 'warning',
      unit: '°C',
      description: 'Coolant above normal operating range.',
    },
    {
      id: 'oil_temp_critical',
      name: 'Oil temp critical',
      field: 'oil_temp',
      op: '>',
      threshold: 125,
      level: 'critical',
      unit: '°C',
      description: 'Oil temperature high enough to break down lubrication.',
    },
    {
      id: 'oil_temp_warning',
      name: 'Oil temp high',
      field: 'oil_temp',
      op: '>',
      threshold: 110,
      level: 'warning',
      unit: '°C',
      description: 'Oil temperature above normal range.',
    },
    {
      id: 'battery_low_critical',
      name: 'Battery critical low',
      field: 'battery_voltage',
      op: '<',
      threshold: 12.4,
      level: 'critical',
      unit: 'V',
      only_when_running: true,
      sustain_s: 10,
      max_gap_s: 5,
      description: 'Charging system not keeping up while engine runs (held 10 s, so a cranking dip is ignored).',
    },
    {
      id: 'battery_high_critical',
      name: 'Battery critical high',
      field: 'battery_voltage',
      op: '>',
      threshold: 15.2,
      level: 'critical',
      unit: 'V',
      only_when_running: true,
      sustain_s: 10,
      max_gap_s: 5,
      description: 'Overcharging for 10 s; likely regulator fault.',
    },
    {
      id: 'battery_low_warning',
      name: 'Battery low',
      field: 'battery_voltage',
      op: '<',
      threshold: 13.2,
      level: 'warning',
      unit: 'V',
      only_when_running: true,
      sustain_s: 10,
      max_gap_s: 5,
      description: 'Below normal charging range (13.2 to 14.8 V) for 10 s while engine runs.',
    },
    {
      id: 'battery_high_warning',
      name: 'Battery high',
      field: 'battery_voltage',
      op: '>',
      threshold: 14.8,
      level: 'warning',
      unit: 'V',
      only_when_running: true,
      sustain_s: 10,
      max_gap_s: 5,
      description: 'Above normal charging range (13.2 to 14.8 V) for 10 s while engine runs.',
    },
    {
      id: 'engine_load_sustained',
      name: 'Engine load sustained',
      field: 'engine_load',
      op: '>',
      threshold: 85,
      level: 'warning',
      unit: '%',
      sustain_s: 60,
      max_gap_s: 5,
      description: 'Engine load stayed above threshold for the whole window.',
    },
    {
      id: 'rpm_high',
      name: 'RPM high',
      field: 'rpm',
      op: '>',
      threshold: 3000,
      level: 'warning',
      unit: 'rpm',
      description: 'Engine revving above normal goods-vehicle range.',
    },
    {
      id: 'overspeed',
      name: 'Overspeed',
      field: 'speed',
      op: '>',
      threshold: 80,
      level: 'warning',
      unit: 'km/h',
      description: 'Above goods-vehicle speed-limiter level.',
    },
  ],
};
